#pragma once

#include "font.h"

#define PKM_COUNT (151)

/// 
typedef enum
{
	SPECIES_MISSINGNO = 0,
	SPECIES_BULBASAUR = 1,
	SPECIES_IVYSAUR = 2,
	SPECIES_VENUSAUR = 3,
	SPECIES_CHARMANDER = 4,
	SPECIES_CHARMELEON = 5,
	SPECIES_CHARIZARD = 6,
	SPECIES_SQUIRTLE = 7,
	SPECIES_WARTORTLE = 8,
	SPECIES_BLASTOISE = 9,
	SPECIES_CATERPIE = 10,
	SPECIES_METAPOD = 11,
	SPECIES_BUTTERFREE = 12,
	SPECIES_WEEDLE = 13,
	SPECIES_KAKUNA = 14,
	SPECIES_BEEDRILL = 15,
	SPECIES_PIDGEY = 16,
	SPECIES_PIDGEOTTO = 17,
	SPECIES_PIDGEOT = 18,
	SPECIES_RATTATA = 19,
	SPECIES_RATICATE = 20,
	SPECIES_SPEAROW = 21,
	SPECIES_FEAROW = 22,
	SPECIES_EKANS = 23,
	SPECIES_ARBOK = 24,
	SPECIES_PIKACHU = 25,
	SPECIES_RAICHU = 26,
	SPECIES_SANDSHREW = 27,
	SPECIES_SANDSLASH = 28,
	SPECIES_NIDORANF = 29,
	SPECIES_NIDORINA = 30,
	SPECIES_NIDOQUEEN = 31,
	SPECIES_NIDORANM = 32,
	SPECIES_NIDORINO = 33,
	SPECIES_NIDOKING = 34,
	SPECIES_CLEFAIRY = 35,
	SPECIES_CLEFABLE = 36,
	SPECIES_VULPIX = 37,
	SPECIES_NINETALES = 38,
	SPECIES_JIGGLYPUFF = 39,
	SPECIES_WIGGLYTUFF = 40,
	SPECIES_ZUBAT = 41,
	SPECIES_GOLBAT = 42,
	SPECIES_ODDISH = 43,
	SPECIES_GLOOM = 44,
	SPECIES_VILEPLUME = 45,
	SPECIES_PARAS = 46,
	SPECIES_PARASECT = 47,
	SPECIES_VENONAT = 48,
	SPECIES_VENOMOTH = 49,
	SPECIES_DIGLETT = 50,
	SPECIES_DUGTRIO = 51,
	SPECIES_MEOWTH = 52,
	SPECIES_PERSIAN = 53,
	SPECIES_PSYDUCK = 54,
	SPECIES_GOLDUCK = 55,
	SPECIES_MANKEY = 56,
	SPECIES_PRIMEAPE = 57,
	SPECIES_GROWLITHE = 58,
	SPECIES_ARCANINE = 59,
	SPECIES_POLIWAG = 60,
	SPECIES_POLIWHIRL = 61,
	SPECIES_POLIWRATH = 62,
	SPECIES_ABRA = 63,
	SPECIES_KADABRA = 64,
	SPECIES_ALAKAZAM = 65,
	SPECIES_MACHOP = 66,
	SPECIES_MACHOKE = 67,
	SPECIES_MACHAMP = 68,
	SPECIES_BELLSPROUT = 69,
	SPECIES_WEEPINBELL = 70,
	SPECIES_VICTREEBEL = 71,
	SPECIES_TENTACOOL = 72,
	SPECIES_TENTACRUEL = 73,
	SPECIES_GEODUDE = 74,
	SPECIES_GRAVELER = 75,
	SPECIES_GOLEM = 76,
	SPECIES_PONYTA = 77,
	SPECIES_RAPIDASH = 78,
	SPECIES_SLOWPOKE = 79,
	SPECIES_SLOWBRO = 80,
	SPECIES_MAGNEMITE = 81,
	SPECIES_MAGNETON = 82,
	SPECIES_FARFETCHD = 83,
	SPECIES_DODUO = 84,
	SPECIES_DODRIO = 85,
	SPECIES_SEEL = 86,
	SPECIES_DEWGONG = 87,
	SPECIES_GRIMER = 88,
	SPECIES_MUK = 89,
	SPECIES_SHELLDER = 90,
	SPECIES_CLOYSTER = 91,
	SPECIES_GASTLY = 92,
	SPECIES_HAUNTER = 93,
	SPECIES_GENGAR = 94,
	SPECIES_ONIX = 95,
	SPECIES_DROWZEE =96 ,
	SPECIES_HYPNO = 97,
	SPECIES_KRABBY = 98,
	SPECIES_KINGLER = 99,
	SPECIES_VOLTORB = 100,
	SPECIES_ELECTRODE = 101,
	SPECIES_EXEGGCUTE = 102,
	SPECIES_EXEGGUTOR = 103,
	SPECIES_CUBONE = 104,
	SPECIES_MAROWAK = 105,
	SPECIES_HITMONLEE = 106,
	SPECIES_HITMONCHAN = 107,
	SPECIES_LICKITUNG = 108,
	SPECIES_KOFFING = 109,
	SPECIES_WEEZING = 110,
	SPECIES_RHYHORN = 111,
	SPECIES_RHYDON = 112,
	SPECIES_CHANSEY = 113,
	SPECIES_TANGELA = 114,
	SPECIES_KANGASKHAN = 115,
	SPECIES_HORSEA = 116,
	SPECIES_SEADRA = 117,
	SPECIES_GOLDEEN = 118,
	SPECIES_SEAKING = 119,
	SPECIES_STARYU = 120,
	SPECIES_STARMIE = 121,
	SPECIES_MRMIME = 122,
	SPECIES_SCYTHER = 123,
	SPECIES_JYNX = 124,
	SPECIES_ELECTABUZZ = 125,
	SPECIES_MAGMAR = 126,
	SPECIES_PINSIR = 127,
	SPECIES_TAUROS = 128,
	SPECIES_MAGIKARP = 129,
	SPECIES_GYARADOS = 130,
	SPECIES_LAPRAS = 131,
	SPECIES_DITTO = 132,
	SPECIES_EEVEE = 133,
	SPECIES_VAPOREON = 134,
	SPECIES_JOLTEON = 135,
	SPECIES_FLAREON = 136,
	SPECIES_PORYGON = 137,
	SPECIES_OMANYTE = 138,
	SPECIES_OMASTAR = 139,
	SPECIES_KABUTO = 140,
	SPECIES_KABUTOPS = 141,
	SPECIES_AERODACTYL = 142,
	SPECIES_SNORLAX = 143,
	SPECIES_ARTICUNO = 144,
	SPECIES_ZAPDOS = 145,
	SPECIES_MOLTRES = 146,
	SPECIES_DRATINI = 147,
	SPECIES_DRAGONAIR = 148,
	SPECIES_DRAGONITE = 149,
	SPECIES_MEWTWO = 150,
	SPECIES_MEW = 151,
} DEX_Species;

/**
 * @brief Retrieves the National Pokdédex based on the species' index.
 * @param index The index of the species.
 * @return The National Pokédex number.
 */
uint8_t pokedexGetNational(uint8_t index);

/**
 * @brief Adds an entry to the owned Pokédex.
 * @param species The species of the Pokémon.
 */
void pokedexAddOwned(uint8_t species);

/**
 * @brief Adds an entry to the seen Pokédex.
 * @param species The species of the Pokémon.
 */
void pokedexAddSeen(uint8_t species);

/**
 * @brief Checks if a Pokémon is from the TPP save.
 * @param species The species of the Pokémon.
 * @param[in] nickname The nickname of the Pokémon.
 * @param[in] otname The name of the original trainer of the Pokémon.
 * @return Whether the Pokémon is from the TPP save.
 * @deprecated Not implemented.
 */
bool pokedexIsFromTPP(uint8_t species, const char8_t* nickname, const char8_t* otname);
